---
title: "PCA"
author: "Donglai Xu"
date: "11/29/2020"
output: word_document
---

```{r}
df1<-read.csv("wineQualityReds.csv")
df2<-read.csv("wineQualityWhites.csv")
df<-rbind(df1[,-1],df2[,-1])
```

```{r}
library(factoextra)
pca <- prcomp(df[,-12], center=TRUE, scale = TRUE)
summary(pca)
```
```{r}
fviz_eig(pca)
# the percentage of variances explained by each principal component.
# PC1 can explain 27.54%, PC2 can explain 22.67%, PC3 can explain 14.15%, PC4 can explain 8.823%.
# Pick the first four component, we will totally have a model that explains 73.187% of the total variability.
```

```{r}
fviz_pca_var(pca,
             col.var = "contrib", # Color by contributions to the PC
             gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"),
             repel = TRUE     # Avoid text overlapping
             )
```

```{r}
# Results for Variables
res.var <- get_pca_var(pca)
#res.var$coord          # Coordinates
res.var$contrib        # Contributions to the PCs
#res.var$cos2           # Quality of representation 
```

```{r}
library(ggbiplot)
df.type<-c(rep("red",1599),rep("white",4898))
```

```{r}
ggbiplot(pca,ellipse=T, groups=df.type,alpha=0.05)
```






